### ISSUE TITLE
clustertree.R and boolean

### ISSUE THREAD

**Issue by njeanne** [zibraproject/zika-pipeline#2]
Hi,
Thanks for your code, it's very useful, but I have a question when using bootstraps of the tree, in the loop of the `prosperi.cluster` function:

```
for(i in 1:length(dfs$order)){
        node <- dfs$order[i]
        ## skip leaves
        if(node < ntips+1){ next }
        ## skip unreliable nodes (if reliability measure is available)
        if(! is.null(reliabilityvec) && reliabilityvec[node-ntips] >= rthresh){ next } 
        ## If the node's subtree is below the threshold, mark it and
        ## its subtree as members of a new cluster
        if(distvec[node-ntips]<=thresh && assign[node]<=0){
            cnum <- cnum+1
            subtree <- graph.dfs(igraph.tree,node,
                                 neimode='out',unreachable=FALSE)$order
            subtree <- subtree[! is.na(subtree)]
            assign[subtree] <- cnum
        }
    }
```

I was wondering if in that R code, at line 57:
`if(! is.null(reliabilityvec) && reliabilityvec[node-ntips] >= rthresh){ next } `
should not be
` if(! is.null(reliabilityvec) && reliabilityvec[node-ntips] < rthresh){ next }`

In the case, we are using a reliablility vector of bootstrap values for the tree which current value of reliabilityvec[node-ntips] is 83 with a reliability threshold, `rthresh`, set to 70. The bootstrap value is over the bootstrap threshold passing the bootstrap condition, then the script should compute the subtree distances to verify the cluster patristic distances are under the percentile distances threshold, `thresh`.

In that case, `! is.null(reliabilityvec)` will be TRUE and `reliabilityvec[node-ntips] >= rthresh` will be TRUE so `if(! is.null(reliabilityvec) && reliabilityvec[node-ntips] >= rthresh){ next } ` is TRUE and the script will enter in the `next` command going to the next node in the DFS and will not compute the distances of the subtree.
Instead with ` if(! is.null(reliabilityvec) && reliabilityvec[node-ntips] < rthresh){ next }`, the result is FALSE and the script will compute the subtree distances as expected.

Maybe, I'm wrong but I don't understand this boolean?

Thanks

**Comment by nickloman** [comment]
Oh hey, this code comes from this source:
https://www.r-bloggers.com/finding-meaningful-clusters-in-phylogenetic-trees-or-other-hierarchical-clusterings/

It's not something we use in our pipeline any more, so we should probably remove it from here.

Please follow up with the author if required?
