### ISSUE TITLE
Nanopore R9 models?

### ISSUE THREAD

**Issue by sdwfrost** [zibraproject/zika-pipeline#4]
I'm trying to pick apart the pipeline to see how it works; where can I get the *.fofn files for `nanopolish eventalign`. It wasn't clear from the Dockerfile.

**Comment by nickloman** [comment]
Should be generated automagically by nanopolish!

Although this stage is deprecated now.. have a look at https://github.com/zibraproject/zika-pipeline/blob/master/scripts/minion.py for the current pipeline.
